stages:
  - build
  - publish

build:
  image: docker:stable
  stage: build
  only:
    - master
  tags:
    - docker-builder
  script:
    - docker build --pull -t ${REGISTRY}/ciag/sendmail:latest .
    - docker push ${REGISTRY}/ciag/sendmail:latest

publish:
  image: docker:stable
  stage: publish
  only:
    - master
  tags:
    - docker-builder
  script:
    - docker pull ${REGISTRY}/ciag/sendmail:latest
    - docker tag ${REGISTRY}/ciag/sendmail:latest ciag/sendmail:latest
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker push ciag/sendmail:latest
